[mcp_servers.sentry]
url = "https://mcp.sentry.dev/mcp"

[mcp_servers.render]
url = "https://mcp.render.com/mcp"
bearer_token_env_var = "RENDER_AUTH_TOKEN"

[mcp_servers.mongodb]
command = "npx"
args = [
  "-y",
  "mongodb-atlas-mcp-remote",
]
env_vars = [
  "MDB_MCP_API_CLIENT_ID",
  "MDB_MCP_API_CLIENT_SECRET",
]

[mcp_servers.stripe]
url = "https://mcp.stripe.com"

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp/"
bearer_token_env_var = "GITHUB_PAT"

[mcp_servers.cloudflare-api]
url = "https://mcp.cloudflare.com/mcp"

[mcp_servers.mailgun]
command = "npx"
args = [
  "-y",
  "@mailgun/mcp-server",
]
env_vars = [
  "MAILGUN_API_KEY",
  "MAILGUN_API_REGION",
]
