development:
  clients:
    default:
      database: dandelion_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: dandelion_test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || ENV['MONGO_URL'] %>
