name: Sentry release

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  sentry-release:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create Sentry release
      uses: getsentry/action-release@v3
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: production